BUILD = /usr/gnat/bin/gprbuild
CLEAN = /usr/gnat/bin/gprclean

# path
default-harness-dir = obj/gnattest/harness
tests-dir = prj_tests
harness-dir = $(tests-dir)/harness

# cmd
TEST = gnattest --tests-dir=../$(tests-dir) --harness-dir=../$(harness-dir)

build-tests = gprbuild -P $(harness-dir)/test_driver.gpr
run-tests = $(harness-dir)/test_runner
