export project_path=$(shell pwd)
export project_root=$(shell dirname $(shell pwd))
export project_name=$(shell basename $(shell pwd))
gpr_file="gpr/$(project_name)_build.gpr"
export exec_name=generate_code
export exec="./bin/$(exec_name)"

local_projects +=
local_projects += code
local_projects += exec
local_projects += model
local_projects += file_io
local_projects += templates
local_projects += string_utils
local_projects += test_utils
local_projects += ada_utils
