export project_path=$(shell pwd)
export project_root=$(shell dirname $(shell pwd))
export project_name=$(shell basename $(shell pwd))
gpr_file="gpr/$(project_name)_build.gpr"
export exec_name=generate_code
export exec="$(project_path)/bin/$(exec_name)"
