BUILD = /usr/gnat/bin/gprbuild -j4 -p
CLEAN = /usr/gnat/bin/gprclean
TEST = /gnattest

harness-dir = gnattest_harness
tests-dir = ../tests

# cmd
TESTS_GENERATE = gnattest --tests-dir=$(tests-dir) --harness-dir=$(harness-dir)
TESTS_BUILD = $(BUILD) obj/$(harness-dir)/test_driver.gpr
TESTS_RUN = obj/$(harness-dir)/test_runner

INSTALL = gprinstall -p
UNINSTALL = gprinstall --uninstall

check2 = $(dir)/$(module)
