export GPR_PROJECT_PATH_FILE=/home/jeremy/workspace/ada/code_generator/projects_list.txt
export project_path=$(shell pwd)
export project_root=$(shell dirname $(shell pwd))
export project_name=$(shell basename $(shell pwd))
gpr_file="gpr/$(project_name)_build.gpr"
export exec_name=generate_code
export exec="./bin/$(exec_name)"

local_projects +=
local_projects += code
local_projects += exec
local_projects += model
local_projects += file_io
local_projects += templates
local_projects += string_utils
local_projects += test_utils
local_projects += ada_utils

project_path_list +=
project_files_list +=

colon := :
empty:=
space := $(empty) $(empty)

concat = $(join $(project_path)/$(prj),)
project_path_list := $(foreach prj,$(local_projects),$(concat))
project_path_list := $(subst $(space),$(colon),$(project_path_list))

concat = $(join $(project_path)/$(prj)/gpr/$(prj).gpr,)
project_files_list := $(foreach prj,$(local_projects),$(concat))
project_files_list := $(subst $(space),$(colon),$(project_files_list))
