export project_path=$(shell pwd)
export project_root=$(shell dirname $(shell pwd))
export project_name=$(shell basename $(shell pwd))
gpr_file="gpr/$(project_name)_build.gpr"
export exec_name=@_PROJECT_NAME_@
export exec="./bin/$(exec_name)"

local_projects +=
@@TABLE@@
local_projects += @_MODULE_@
@@END_TABLE@@
