MAKE=python.exe ../build/make.py

all: compil run

check::
	echo make file="filename" check
	@$(MAKE) $@ $(file)

compil::
	@$(MAKE) $@

run::
	@$(MAKE) $@

clean::
	@$(MAKE) $@

install::
	@$(MAKE) $@

uninstall::
	@$(MAKE) $@
